// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/visa/v1/visa.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_api_visa_v1_visa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_visa_v1_visa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_api_visa_v1_visa_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_api_visa_v1_visa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_visa_v1_visa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_api_visa_v1_visa_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_api_visa_v1_visa_proto protoreflect.FileDescriptor

const file_api_visa_v1_visa_proto_rawDesc = "" +
	"\n" +
	"\x16api/visa/v1/visa.proto\x12\vapi.visa.v1\x1a\x1cgoogle/api/annotations.proto\"#\n" +
	"\vEchoRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"$\n" +
	"\fEchoResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value2c\n" +
	"\vVisaService\x12T\n" +
	"\x04Echo\x12\x18.api.visa.v1.EchoRequest\x1a\x19.api.visa.v1.EchoResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/rpc/v1/echoB,Z*github.com/forgoes/proto-go/api/visa/v1;v1b\x06proto3"

var (
	file_api_visa_v1_visa_proto_rawDescOnce sync.Once
	file_api_visa_v1_visa_proto_rawDescData []byte
)

func file_api_visa_v1_visa_proto_rawDescGZIP() []byte {
	file_api_visa_v1_visa_proto_rawDescOnce.Do(func() {
		file_api_visa_v1_visa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_visa_v1_visa_proto_rawDesc), len(file_api_visa_v1_visa_proto_rawDesc)))
	})
	return file_api_visa_v1_visa_proto_rawDescData
}

var file_api_visa_v1_visa_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_visa_v1_visa_proto_goTypes = []any{
	(*EchoRequest)(nil),  // 0: api.visa.v1.EchoRequest
	(*EchoResponse)(nil), // 1: api.visa.v1.EchoResponse
}
var file_api_visa_v1_visa_proto_depIdxs = []int32{
	0, // 0: api.visa.v1.VisaService.Echo:input_type -> api.visa.v1.EchoRequest
	1, // 1: api.visa.v1.VisaService.Echo:output_type -> api.visa.v1.EchoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_visa_v1_visa_proto_init() }
func file_api_visa_v1_visa_proto_init() {
	if File_api_visa_v1_visa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_visa_v1_visa_proto_rawDesc), len(file_api_visa_v1_visa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_visa_v1_visa_proto_goTypes,
		DependencyIndexes: file_api_visa_v1_visa_proto_depIdxs,
		MessageInfos:      file_api_visa_v1_visa_proto_msgTypes,
	}.Build()
	File_api_visa_v1_visa_proto = out.File
	file_api_visa_v1_visa_proto_goTypes = nil
	file_api_visa_v1_visa_proto_depIdxs = nil
}
