// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/common/v1/errors.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BusinessErrorCode int32

const (
	BusinessErrorCode_BUSINESS_ERROR_CODE_UNSPECIFIED    BusinessErrorCode = 0
	BusinessErrorCode_BUSINESS_ERROR_CODE_VISA_INVALID   BusinessErrorCode = 1
	BusinessErrorCode_BUSINESS_ERROR_CODE_PERMIT_EXPIRED BusinessErrorCode = 2
)

// Enum value maps for BusinessErrorCode.
var (
	BusinessErrorCode_name = map[int32]string{
		0: "BUSINESS_ERROR_CODE_UNSPECIFIED",
		1: "BUSINESS_ERROR_CODE_VISA_INVALID",
		2: "BUSINESS_ERROR_CODE_PERMIT_EXPIRED",
	}
	BusinessErrorCode_value = map[string]int32{
		"BUSINESS_ERROR_CODE_UNSPECIFIED":    0,
		"BUSINESS_ERROR_CODE_VISA_INVALID":   1,
		"BUSINESS_ERROR_CODE_PERMIT_EXPIRED": 2,
	}
)

func (x BusinessErrorCode) Enum() *BusinessErrorCode {
	p := new(BusinessErrorCode)
	*p = x
	return p
}

func (x BusinessErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BusinessErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_v1_errors_proto_enumTypes[0].Descriptor()
}

func (BusinessErrorCode) Type() protoreflect.EnumType {
	return &file_api_common_v1_errors_proto_enumTypes[0]
}

func (x BusinessErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BusinessErrorCode.Descriptor instead.
func (BusinessErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_common_v1_errors_proto_rawDescGZIP(), []int{0}
}

type BusinessError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          BusinessErrorCode      `protobuf:"varint,1,opt,name=code,proto3,enum=api.common.v1.BusinessErrorCode" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessError) Reset() {
	*x = BusinessError{}
	mi := &file_api_common_v1_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessError) ProtoMessage() {}

func (x *BusinessError) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessError.ProtoReflect.Descriptor instead.
func (*BusinessError) Descriptor() ([]byte, []int) {
	return file_api_common_v1_errors_proto_rawDescGZIP(), []int{0}
}

func (x *BusinessError) GetCode() BusinessErrorCode {
	if x != nil {
		return x.Code
	}
	return BusinessErrorCode_BUSINESS_ERROR_CODE_UNSPECIFIED
}

func (x *BusinessError) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BusinessError) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

var File_api_common_v1_errors_proto protoreflect.FileDescriptor

const file_api_common_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/common/v1/errors.proto\x12\rapi.common.v1\"u\n" +
	"\rBusinessError\x124\n" +
	"\x04code\x18\x01 \x01(\x0e2 .api.common.v1.BusinessErrorCodeR\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain*\x86\x01\n" +
	"\x11BusinessErrorCode\x12#\n" +
	"\x1fBUSINESS_ERROR_CODE_UNSPECIFIED\x10\x00\x12$\n" +
	" BUSINESS_ERROR_CODE_VISA_INVALID\x10\x01\x12&\n" +
	"\"BUSINESS_ERROR_CODE_PERMIT_EXPIRED\x10\x02B3Z1example.com/project/gen/go/api/common/v1;commonv1b\x06proto3"

var (
	file_api_common_v1_errors_proto_rawDescOnce sync.Once
	file_api_common_v1_errors_proto_rawDescData []byte
)

func file_api_common_v1_errors_proto_rawDescGZIP() []byte {
	file_api_common_v1_errors_proto_rawDescOnce.Do(func() {
		file_api_common_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_common_v1_errors_proto_rawDesc), len(file_api_common_v1_errors_proto_rawDesc)))
	})
	return file_api_common_v1_errors_proto_rawDescData
}

var file_api_common_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_common_v1_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_common_v1_errors_proto_goTypes = []any{
	(BusinessErrorCode)(0), // 0: api.common.v1.BusinessErrorCode
	(*BusinessError)(nil),  // 1: api.common.v1.BusinessError
}
var file_api_common_v1_errors_proto_depIdxs = []int32{
	0, // 0: api.common.v1.BusinessError.code:type_name -> api.common.v1.BusinessErrorCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_common_v1_errors_proto_init() }
func file_api_common_v1_errors_proto_init() {
	if File_api_common_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_common_v1_errors_proto_rawDesc), len(file_api_common_v1_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_common_v1_errors_proto_goTypes,
		DependencyIndexes: file_api_common_v1_errors_proto_depIdxs,
		EnumInfos:         file_api_common_v1_errors_proto_enumTypes,
		MessageInfos:      file_api_common_v1_errors_proto_msgTypes,
	}.Build()
	File_api_common_v1_errors_proto = out.File
	file_api_common_v1_errors_proto_goTypes = nil
	file_api_common_v1_errors_proto_depIdxs = nil
}
